### ISSUE TITLE
suggestion hud

### ISSUE THREAD

**Issue by lostopkk** [SrGnis/Body-Health-System#21]
hello! I just wanted to suggest being able to reduce the size of the character in the hud and if he could stay behind the chat so I could read it, thanks! (and key bind to open hud to see what's wrong with my character.)

**Comment by makumaku1974** [comment]
Will this also be compatible with Autohud? It's basically an Immersive Hud mod for Fabric.

**Comment by SrGnis** [comment]
Done in 764ff83

**Comment by SrGnis** [comment]
@makumaku1974 AutoHUD don't affect BHS. I will check if easy add compability
